//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootcampBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deneme
    {
        public int Id { get; set; }
        public string deneme1 { get; set; }
        public string deneme2 { get; set; }
        public string deneme33 { get; set; }
    }
}
